[workspace]
members = [
    "carbide_core",
    "carbide_controls",
    "carbide_derive",
    "backends/carbide_example_shared",
    "backends/carbide_winit",
    #"backends/carbide_gfx",
    "backends/carbide_glium",
    # "backends/carbide_piston",
    # "backends/carbide_rendy",
    # "backends/carbide_vulkano",
    "backends/carbide_wgpu",
    "carbide",
    "carbide_macro"
]
