[package]
name = "lines"
version.workspace = true
repository.workspace = true
edition.workspace = true
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carbide = { path = "../../carbide", features = ["controls"] }
euclid = "0.20.13"
smol_str = "0.1.15"
approx = "0.3.2"